POST  http://localhost:5000/api/v1/networks/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNhcmxvc2tydCIsInVpZCI6IjYzNDEwYjNiODVkOTNkMmQyMzk2MGNiYSIsImlhdCI6MTY2NTI5NzMwNiwiZXhwIjoxNjY3ODg5MzA2fQ.h5MAFWSZQotTBg9FKFCNJgzg1e7ao2-9Oqke5CO9BRo

{
    "name" : "Twitter",
    "url" : "https://twitter.com/carloskrt"
}