POST http://localhost:5000/api/v1/networks/create-socialnetwork
content-type: application/json

{
    "name" : "Facebook",
    "url" : "https://facebook.com/sdfdsfsdf",
    "userId" : "62e89a47275ae3d5df03aae1"
}