POST http://localhost:5000/api/v1/auth/register
content-type: application/json

{
    "username": "maria",
    "email" : "maria@gmail.com",
    "password" : "maria123",
    "confirmPassword" : "maria123"
}