GET http://localhost:5000/api/v1/auth/renew-token
content-type: application/json
//Authorition with Bearer token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYyZTg5YTQ3Mjc1YWUzZDVkZjAzYWFlMSIsInVzZXJuYW1lIjoiY2Fyb2xpbmEiLCJwYXNzd29yZCI6IiQyYSQxMCRlb05KeWQzaWNnTnlYTlhuZzA3ZFFlTFlMc3d2dy9SNXBZR0NleE1iMFlWdUdRMTlJcGpWdSIsImVtYWlsIjoiY2Fyb2xpbmFAZ21haWwuY29tIiwibmV0d29ya3MiOltdLCJfX3YiOjB9LCJpYXQiOjE2NTk0MTE1ODUsImV4cCI6MTY2MjAwMzU4NX0.w1PZGSn77D1f8UIUYI7Ztz9QhVSMGq8Z_3QMLURRHpI


