GET http://localhost:5000/api/v1/auth/renew-token
content-type: application/json
//Authorition with Bearer token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYyZTg1NDMxNDU5MTAzMGVkNDcwMDBhZSIsInVzZXJuYW1lIjoiY2FybG9zY2FycmV0ZSIsInBhc3N3b3JkIjoiJDJhJDEwJEg5WnBtcFZaNEppZDFyLkVOY1BmaC52VG9sdjJPR3dhLm4zaHRDdDRtc3FtRDBXUksuZE02IiwiZW1haWwiOiJjYXJsb3NjYXJyZXRlLnNjQGdtYWlsLmNvbSIsIm5ldHdvcmtzIjpbXSwiX192IjowfSwiaWF0IjoxNjU5MzkzMjg5LCJleHAiOjE2NjE5ODUyODl9.Jp8hIw1ymFUFdGmSMJ6sX-0Jpsj0sKsdTLewcmKy9AA


